doudesu: remove class in status tr tag this fix error AttributeError: 'NoneType' object has no attribute 'a' class tr status is none so remove that for fix error while choose manga :b
Signed-off-by: picasso09 <picasso09DV@proton.me>

Date:      Thu Apr 10 20:23:27 2025 +0700
Change-Id: 06000232450972450fb3bf17efd4faea050b6b33